### ISSUE TITLE
Reactivity does not work

### ISSUE THREAD

**Issue by akaiworld** [VeliovGroup/neo4j-fiber#2]
I use neo4j-fiber with ccorcos:any-db.
Here is my code:

SERVER: 

``` js
let c = db.query({
cypher:  MATCH (node) RETURN node.id as _id, node.id, node.topic , 
reactive: true, 
});
AnyDb.publish('allNodes', ( data ) => {
return c.fetch();
});
```

CLIENT: 

``` js
Session.set('nodes', 'loading');
let subscripiton = AnyDb.subscribe('allNodes', {data: 'AKAI'}, ( sub ) => {
    log("sub ready");
    Session.set('nodes', sub.data);
    sub.onChange( (data) => {
        log("new sub data")
        Session.set('nodes', data);
    });
}); 
export default createContainer(() => {
    return {
        nodes: Session.get('nodes'), 
    };
}, EventsListPage);
```

Data is fetched only once, but when i add some nodes to the DB directly - nothing updates reactivelly. Only when i refresh the page data does update.

**Comment by dr-dimitru** [comment]
Not sure about compatibility with meteor-any-db package
"Reactivity" in `neo4j-fiber` is a bit different from reactivity in Meteor.
Data and cursors with `reactive` flag re-validated when requested during runtime on Server.
Hope that helps.

Closing this issue as old one - fell are to reopen it
