### ISSUE TITLE
Nested arrays are not parsed into Neo4jNode class

### ISSUE THREAD

**Issue by ogroppo** [VeliovGroup/neo4j-fiber#6]
Arrays are returned raw as per neo4j REST reply.
When mixing results (i.e. with collect function) in a single row only the top level entity (node or rel) is parsed into a plain object.

This means that metadata and data are in different object keys along with unuseful data:
<img width="432" alt="collect_results" src="https://cloud.githubusercontent.com/assets/4820803/22306737/3d513fc4-e338-11e6-9195-1179fcb28e99.png">

**Comment by dr-dimitru** [comment]
Hello @bummo ,

Could you please provide sample data, and a cypher query, which causes such results

**Comment by ogroppo** [comment]
Any data, query is simply 	
var d = db.query("MATCH (n) RETURN collect(n)").fetch()[0];
console.log(d); // { 'collect(n)': [{...},{...}] }

Just noticed other issue:
If I give an alias to the collection e.g "MATCH (n) RETURN collect(n) as nodes" the result is 
{ nodes: undefined }

**Comment by dr-dimitru** [comment]
Hello @bummo ,

Sorry for delay with publish, faced hardware malfunction, had to fix my old Mac.

Please test it on your end, let me know if it's solved for you

**Comment by ogroppo** [comment]
Hi @dr-dimitru,

I think we are getting there, however, the collect function now returns a Neo4jNode Class, which is again not what expected because the query has been run with '.fetch()' so the outcome should not be a cursor.
So for every collect query an iterative '.get()' function has to be called to get the actual node.

Let me know if this is going to be complicated & Thanks for update

**Comment by dr-dimitru** [comment]
Hello @bummo ,

You're right, going to fix it now

**Comment by dr-dimitru** [comment]
Hello @bummo ,

Should be fixed now, feel free to reopen this issue.
Thank you for your patience.

**Comment by ogroppo** [comment]
Thanks @dr-dimitru, works nicely.

I've just noticed that labels are returned as an indexed object rather than an array of strings, not a big deal of course, just a remark.

**Comment by dr-dimitru** [comment]
Hello @bummo ,

> labels are returned as an indexed object rather than an array of strings

With the same query?

```cypher
MATCH (n) RETURN collect(n)
```

**Comment by ogroppo** [comment]
@dr-dimitru apologies... my debugger considers Arrays as Objects. (which is technically true)

**Comment by dr-dimitru** [comment]
@bummo no worries, thank you for contribution.
